#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path:         /
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/home.html.twig

about:
    path:         /a-propos
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/about.html.twig

gallery:
    path:         /galerie
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/gallery.html.twig

gallery_watercolors:
    path:         /galerie-aquarelles
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/gallery.html.twig

gallery_paintings:
    path:         /galerie-paintings
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/gallery.html.twig


gallery_pastel:
    path:         /galerie-pastels
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/gallery.html.twig


order:
    path:         /commande
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/order.html.twig


contact:
    path:         /contact
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/contact.html.twig